export const Images = {
    woodenChair: require("../Assets/png/woodchair.png"),
    table: require("../Assets/png/wtable.png"),
    lamp: require("../Assets/png/lamp.png"),
    sofa: require("../Assets/png/sofa.png"),
    bed: require("../Assets/png/bed.png"),
    shirt: require("../Assets/png/shirt.png"),
    pants: require("../Assets/png/pants.png"),
    shoes: require("../Assets/png/shoes.png"),
    watch: require("../Assets/png/watch.png"),
    dress: require("../Assets/png/dress.png"),
    handbag: require("../Assets/png/handbag.png"),
    heels: require("../Assets/png/heels.png"),
    jewelry: require("../Assets/png/jewellery.png"),
    smartphone: require("../Assets/png/phone-1.png"),
    laptop: require("../Assets/png/laptop.png"),
    headphones: require("../Assets/png/headphones.png"),
    camera: require("../Assets/png/camera.png"),
    carTires: require("../Assets/png/cartires.png"),
    carBattery: require("../Assets/png/batteies.png"),
    helmet: require("../Assets/png/helmet1.png"),
    logoInner: require("../Assets/png/nerves.png"),
    logoMain: require("../Assets/png/nerveslogo.png"),
}